### ISSUE TITLE
unmatched_primary_count and unmatched_secondary_count incorrectly being equal

### ISSUE THREAD

**Issue by Tayhm** [quarkslab/python-bindiff#8]
Hi,
when using the unmatched_primary_count and unmatched_secondary_count attributes of a diff, they are incorrectly equal. I believe this is the case for all samples.
To replicate:

```
from bindiff import BinDiff
import os

os.environ["IDA_PATH"] = "C:\Program Files\IDA Pro 8.3"

diff = BinDiff.from_binary_files(
    "37e3a07a17a82175c60992f18eaf169e4014915eb90fac5b4704060572cfa60b",
    "70d956079d0bec352b92b370c527fec34f9e5c3bfe0217e551d49c5784257d1c",
    "abc",
)

print(diff.unmatched_primary_count)
print(diff.unmatched_secondary_count)
```

The filenames are the hashes of the files used, both are available on VirusTotal. When using Bindiff manually in IDA, there are 83 primary unmatched functions and 1 secondary unmatched function. Both print statements output 83 though.

**Comment by RobinDavid** [comment]
Thanks for pinpointing that issue.

We were loading twice the same entry for ``primary_file`` and ``secondary_file``, resulting in the improper result in unmatched attributes.

I fixed it and published a new release: https://github.com/quarkslab/python-bindiff/releases/tag/v0.3.0

Thank you for the feedback!

**Comment by Tayhm** [comment]
Thank you!
